# spring
servlet.contextPath=/nacos
server.port=8848

# 字符集配置
spring.http.encoding.charset=utf-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.charset=utf-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# 数据库配置
spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://mysql-nacos:3306/ly_factmesh_nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
db.user.0=nacos
db.password.0=nacos

# 连接池配置
db.pool.config.connectionTimeout=30000
db.pool.config.validationTimeout=10000
db.pool.config.maximumPoolSize=20
db.pool.config.minimumIdle=2

# 控制台配置
nacos.console.ui.enabled=true
nacos.core.auth.enabled=false
nacos.core.auth.enable.userAgentAuthWhite=true
nacos.core.auth.ignore.urls=/**

# 关闭缓存
nacos.core.caching.enabled=false
nacos.core.auth.caching.enabled=false
