server:
  port: 9089

spring:
  application:
    name: mom-simulator
  profiles:
    active: dev
  config:
    import: optional:nacos:simulator.yaml
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: LY_MOM_GROUP
        username: nacos
        password: nacos
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: LY_MOM_GROUP
        username: nacos
        password: nacos

# 数据模拟器配置（仅开发环境使用，生产环境不部署此模块）
simulator:
  opcua:
    enabled: true
    host: "0.0.0.0"
    port: 4840
  modbus:
    enabled: true
    host: "0.0.0.0"
    port: 502
