# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ai_service.proto\x12\x02\x61i\"\x18\n\x16GetCapabilitiesRequest\"M\n\nCapability\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"n\n\x17GetCapabilitiesResponse\x12\x0e\n\x06module\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12$\n\x0c\x63\x61pabilities\x18\x04 \x03(\x0b\x32\x0e.ai.Capability\"\\\n\x0cTrainRequest\x12\x0e\n\x06\x65pochs\x18\x01 \x01(\x05\x12\n\n\x02lr\x18\x02 \x01(\x01\x12\x1f\n\x07train_x\x18\x03 \x03(\x0b\x32\x0e.ai.FloatArray\x12\x0f\n\x07train_y\x18\x04 \x03(\x05\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\"c\n\rTrainResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x65pochs\x18\x02 \x01(\x05\x12\n\n\x02lr\x18\x03 \x01(\x01\x12\x12\n\nfinal_loss\x18\x04 \x01(\x01\x12\x12\n\nmodel_path\x18\x05 \x01(\t\".\n\x0ePredictRequest\x12\x1c\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0e.ai.FloatArray\"J\n\x0fPredictResponse\x12\"\n\ninput_data\x18\x01 \x03(\x0b\x32\x0e.ai.FloatArray\x12\x13\n\x0bpredictions\x18\x02 \x03(\x05\x32\xb9\x01\n\tAiService\x12J\n\x0fGetCapabilities\x12\x1a.ai.GetCapabilitiesRequest\x1a\x1b.ai.GetCapabilitiesResponse\x12,\n\x05Train\x12\x10.ai.TrainRequest\x1a\x11.ai.TrainResponse\x12\x32\n\x07Predict\x12\x12.ai.PredictRequest\x1a\x13.ai.PredictResponseB)\n\x17\x63om.ly.factmesh.ai.grpcB\x0e\x41iServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.ly.factmesh.ai.grpcB\016AiServiceProto'
  _globals['_GETCAPABILITIESREQUEST']._serialized_start=30
  _globals['_GETCAPABILITIESREQUEST']._serialized_end=54
  _globals['_CAPABILITY']._serialized_start=56
  _globals['_CAPABILITY']._serialized_end=133
  _globals['_GETCAPABILITIESRESPONSE']._serialized_start=135
  _globals['_GETCAPABILITIESRESPONSE']._serialized_end=245
  _globals['_TRAINREQUEST']._serialized_start=247
  _globals['_TRAINREQUEST']._serialized_end=339
  _globals['_FLOATARRAY']._serialized_start=341
  _globals['_FLOATARRAY']._serialized_end=369
  _globals['_TRAINRESPONSE']._serialized_start=371
  _globals['_TRAINRESPONSE']._serialized_end=470
  _globals['_PREDICTREQUEST']._serialized_start=472
  _globals['_PREDICTREQUEST']._serialized_end=518
  _globals['_PREDICTRESPONSE']._serialized_start=520
  _globals['_PREDICTRESPONSE']._serialized_end=594
  _globals['_AISERVICE']._serialized_start=597
  _globals['_AISERVICE']._serialized_end=782
# @@protoc_insertion_point(module_scope)
